---

# mod_http2 is not yet included with standard apache2 package.
# Different branch is needed. See: https://launchpad.net/~ondrej/+archive/ubuntu/apache2
- name: Set Apache repository
  apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: Apache install
  apt:
    name: apache2

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
     - deflate
     - expires
     - headers
     - http2
     - socache_shmcb

- name: Enable Apache startup
  service:
    name: apache2
    enabled: yes

- name: Restart apache
  service:
    name: apache2
    state: restarted
