---

# mod_http2 is not yet included with standard apache2 package.
# Different branch is needed. See: https://launchpad.net/~ondrej/+archive/ubuntu/apache2
- name: Apache repository set
  apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: Apache installed
  apt:
    name: apache2

- name: Apache modules config set
  template:
    src: "roles/apache/templates/{{ item }}.conf.j2"
    dest: "/etc/apache2/mods-available/{{ item }}.conf"
  with_items:
    - expires
  notify:
    - Restart Apache

- name: Apache modules enabled
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - deflate
    - expires
    - headers
    - http2
    - rewrite
    - socache_shmcb
  notify:
    - Restart Apache

- name: Apache started & enabled on boot
  service:
    name: apache2
    state: started
    enabled: yes
