---

### TEMPORARY MEASURE ###
# Ubuntu no longer supports python 2.7 that
# Ansible needs. As such, this bootstrapping
# task is needed.
- name: Ansible bootstrap
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Update apt
      raw: apt-get update -qq
    - name: Install python 2.7 (Ansible bootstap)
      raw: apt-get install --no-install-recommends --assume-yes python-apt

- name: Deploy
  hosts: webservers
  become: yes
  become_method: sudo
  roles:
    - common
    - ssh
    - ufw
    - apache
    - fail2ban
    - node
    - bower
    - polymer
  tasks:
    - include: roles/git/tasks/pull.yml
      when: "'dev' not in group_names" # Don't GIT pull on development machines
    - include: roles/bower/tasks/update.yml
    - include: roles/polymer/tasks/build.yml
      when: "'dev' not in group_names" # Don't Polymer build on development machines
    - include: roles/apache/tasks/virtualhost.yml
    - include: roles/letsencrypt/tasks/main.yml
