---

#- name: Set Node repository key
#  apt_key:
#    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#
#- name: Set Node repository
#  apt_repository:
#    repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
#
#- name: Node Install
#  apt:
#    name: nodejs # nodejs package has $PATH issues

- name: NPM Install
  apt:
    name: npm

# Install n before NPM update as non-apt version requires Node
- name: n install
  npm:
    name: n
    global: yes

# TODO: n doesn't give feedback when the version is changed (only when it's downloaded).
# Consider trying alternatives like NVM
- name: Node install
  command: "n {{ node_version }}"
  register: nodeinstall
  changed_when: "nodeinstall.stdout != ''"

- name: Set NPM version
  npm:
    name: npm
    global: yes
    version: "{{ npm_version }}"
